### ISSUE TITLE
find() doesn't search in symlink folders

### ISSUE THREAD

**Issue by astoilkov** [szwacz/fs-jetpack#70] opened 2018-07-09 14:46 UTC
I have a folder which I search in with `find()`. In that folder, there is a symlinked folder which has files inside. `find()` doesn't return the files that match which are inside of the symlinked folder

**Comment by szwacz** [comment] 2018-07-09 14:55
By design it should work, this case is covered by test (although only one and very basic) and there is a `symlink` flag to alter this behaviour: https://github.com/szwacz/fs-jetpack#findpath-searchoptions

You can tinker with this test: https://github.com/szwacz/fs-jetpack/blob/master/spec/find.spec.js#L265 to track down the problem a little more.

**Comment by szwacz** [comment] 2018-07-09 15:04
I take that back. Wrote quite simple test, and indeed somethign is not quite right when searching in symlinked directories. Will inwestigate.

**Comment by szwacz** [comment] 2018-07-10 11:12
Fixed in v2.0.0, now there is no option to configure this behaviour, and `find()` always follows symlinks.

**Closed by szwacz** 2018-07-10 11:12 UTC

**Comment by astoilkov** [comment] 2018-07-10 17:21
Ok. Great. Just for reference - [glob](https://github.com/isaacs/node-glob#options) has a `follow` option to enable this functionality. Maybe it is a good idea to that because as described in their documentation it is possible to make duplicates when following symlinks.
